name = "saXMin"
license = "MIT"
licenselink = "https://github.com/satjd/hugo-saxmin/blob/master/LICENSE.md"
description = "A fork of yihui's hugo-xmin theme."
homepage = "http://satjd.xyz"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "satjd"
  homepage = "http://satjd.xyz"
